### ISSUE TITLE
Error: Invalid configuration - Anki ⁨2.1.54/Qt 6.3.1

### ISSUE THREAD

**Issue by hienstorfer** [Garbaz/anki-merge-duplicates#4]
Addon drops error "invalid configuration" and anki freezes with following configuration:

Version ⁨2.1.54 (b6a7760c)⁩
Python 3.9.7 Qt 6.3.1 PyQt 6.3.1

I used Addon with earlier versions of Anki sucessfully.
Regards, Philipp

**Comment by Garbaz** [comment]
What is the configuration of the addon? (`Tools` -> `Addons` -> `merge_duplicates` -> `Config`)

It should look this:
```
{
    "merge_mode": "longer"
}
```
or instead of `"longer"`, it could be `"concat"`, or `"skip"`.

Regards,
Tobi :)

**Comment by Garbaz** [comment]
This should be fixed by PR #5
